---
driver:
  name: vagrant
  vm_hostname: freeipa.ci.kitchenci
  use_sudo: false
  customize:
    memory: 1024

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  dependencies:
    - name: openssh
      repo: git
      source: https://github.com/salt-formulas/salt-formula-openssh
  log_level: error
  formula: freeipa
  grains:
    noservices: true
  state_top:
    base:
      "*":
        - freeipa
  pillars:
    top.sls:
      base:
        "*":
          - freeipa
          - openssh_server
  pillars-from-files:
    openssh_server.sls: tests/pillar/openssh_server.sls
  init_environment: |
    echo "10.0.2.15  freeipa2.ci.kitchenci | sudo tee -a /etc/hosts"


platforms:
- name: ubuntu-14.04
- name: ubuntu-16.04
- name: centos-6.8
- name: centos-7.3

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
