sudo: required
services:
  - docker

addons:
  apt:
    packages:
    - apt-transport-https

install:
  - pip install PyYAML
  - pip install virtualenv
  - |
    test -e Gemfile || cat <<EOF > Gemfile
    source 'https://rubygems.org'
    gem 'rake'
    gem 'test-kitchen'
    gem 'kitchen-docker'
    gem 'kitchen-inspec'
    gem 'inspec'
    gem 'kitchen-salt'   #, :git => 'https://github.com/salt-formulas/kitchen-salt.git'
  - bundle install

env:
    - PLATFORM=epcim/salt:saltstack-centos-7-salt-stable PLATFORM_NAME:centos
    - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-stable PLATFORM_NAME:ubuntu
    - PLATFORM=epcim/salt:saltstack-ubuntu-bionic-salt-stable

before_script:
  - set -o pipefail
  - make test | tail

script:
  - test ! -e .kitchen.yml || bundle exec kitchen converge ${SUITE} || true
  - test ! -e .kitchen.yml || bundle exec kitchen verify ${SUITE} -t tests/integration

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6123573504759330786b
    on_success: change # options: [always|never|change] default: always
    on_failure: never  # options: [always|never|change] default: always
    on_start: never    # options: [always|never|change] default: always
    on_cancel: never   # options: [always|never|change] default: always
    on_error: never    # options: [always|never|change] default: always
  email: false
